name: Release to GitHub

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: New Release
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-ci.txt

      - name: Make pyinstaller binary
        run: |
          pyinstaller ./main.spec
          copy sounds ./dist/launchtype

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/launchtype/*
          tag_name: ${{ github.ref }}
          body: |
            This is a new release of LaunchType. For the user manual see https://www.oriolgomez.com/software/
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          